export { registerHealthRoutes } from './health';
export { registerScanRoutes } from './scans';
export { registerFindingsRoutes } from './findings';
export { registerRemediationRoutes } from './remediation';
export { registerBaselineRoutes } from './baseline';
export { registerDashboardRoutes } from './dashboard';
export { registerControllerRoutes } from './controller';
export { registerProfileRoutes } from './profiles';
export { registerInventoryRoutes } from './inventory';
export { registerArtifactRoutes } from './artifacts';
export type { RouterDependencies, SharedState } from './types';
