compressionLevel: 0

enableGlobalCache: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs

# Critical log filtering - suppress peer dependency validation errors
logFilters:
  # Missing peer dependencies (YN0002)
  - code: YN0002
    level: discard
  # Version mismatch warnings (YN0060) 
  - code: YN0060
    level: discard
  # Incorrect peer dependency warnings (YN0086)
  - code: YN0086
    level: discard
  # Package build failures (YN0009)
  - code: YN0009
    level: discard
  # Build warnings (YN0007)
  - code: YN0007
    level: discard

httpRetry: 3
