#!/usr/bin/env sh
# Reject Co-authored-by trailers that attribute AI coding tools.
# Human co-authors are allowed; use Assisted-by for AI assistance instead.
set -eu

commit_msg_file="${1:-${PRE_COMMIT_COMMIT_MSG_FILENAME:-}}"

if [ -z "$commit_msg_file" ] || [ ! -f "$commit_msg_file" ]; then
  echo "check-commit-attribution: missing commit message file" >&2
  exit 1
fi

ai_coauthor_pattern='^co-authored-by:.*(claude|anthropic|cursor|copilot|github-copilot|openai|chatgpt|gpt-|gemini|codex|windsurf|cody|devin|aider|tabnine|sourcegraph|continue-dev|amazon[[:space:]]q|codeium|replit|bolt\.new|\[bot\]|@anthropic\.com|@cursor\.com|@openai\.com|@github\.com/apps/)'

violations="$(grep -iE "$ai_coauthor_pattern" "$commit_msg_file" || true)"

if [ -n "$violations" ]; then
  echo "commit-msg: Co-authored-by is not allowed for AI tools." >&2
  echo >&2
  echo "Use one of these instead (no email required):" >&2
  echo "  Assisted-by: <name of code assistant>" >&2
  echo "  Generated by <name of code assistant>" >&2
  echo >&2
  echo "Offending trailer(s):" >&2
  echo "$violations" | sed 's/^/  /' >&2
  exit 1
fi

exit 0
