---
# See https://github.com/ansible/team-devtools/blob/main/.github/workflows/ack.yml
name: ack

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  ack:
    uses: ansible/team-devtools/.github/workflows/ack.yml@e8d1c4af26f45704b717f4b10b7d99ece796e2d3 # main
    secrets: inherit
